# @package _global_
env:
  parallel_envs: 10
  dummy_vecenv: true

algorithm:
  _target_: ac_maxq.train.main
  model:
    actor:
      layers:
        - 64
        - 64
    critic:
      layers:
        - 64
        - 64

    device : "cpu"  # a pytorch device ("cpu" or "cuda")

  lr: 3.e-4
  optim_eps: 0.00001

  n_steps: 10
  gamma: 0.99
  entropy_coef: 0.01
  value_loss_coef: 0.5
  use_proper_termination: False
  standarize_returns: False
  optim_coef: 0.5
