defaults:
  - logger: filesystemlogger
  - hydra/job_logging: file

hydra:
  run:
    dir: outputs/${env.name}-${algorithm.name}-${seed}-${now:%Y-%m-%d_%H-%M-%S}

seed: null

algorithm:
  total_steps: 100_000
  log_interval: 10_000
  save_interval: 10_000
  eval_interval: 10_000
  eval_episodes: 5
  video_interval: False
  video_frames: 500

env:
  _target_: utils.envs.make_env
  name : ???
  time_limit : ???
  wrappers :
    - ClearInfo
    - RecordEpisodeStatistics
    - SquashDones
